// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuEUcRy5yolZDuH1lNr_p8Cw9iau8JQ9g',
    appId: '1:877086975035:android:51a797bcaaa8c327d4a81e',
    messagingSenderId: '877086975035',
    projectId: 'tatti-til',
    storageBucket: 'tatti-til.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm6e33axpCGzq91QOF_T0HLG2qRakzoFo',
    appId: '1:877086975035:ios:d833d433e3745c44d4a81e',
    messagingSenderId: '877086975035',
    projectId: 'tatti-til',
    storageBucket: 'tatti-til.firebasestorage.app',
    iosBundleId: 'com.tattitil.app',
  );
}
