// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH-oVk7alMDl2-c_TYcNTL67O-rYzWpzo',
    appId: '1:63012545079:android:a65325a3fe14529be9d5b2',
    messagingSenderId: '63012545079',
    projectId: 'dciplatforma',
    storageBucket: 'dciplatforma.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoSXX91vEwtL3B7LZTgbtLxo6D8v7-xw8',
    appId: '1:63012545079:ios:1e80d1b33c3c922ce9d5b2',
    messagingSenderId: '63012545079',
    projectId: 'dciplatforma',
    storageBucket: 'dciplatforma.firebasestorage.app',
    androidClientId: '63012545079-4h2nvplfq12rb4q51hidleeq9p94lgvc.apps.googleusercontent.com',
    iosClientId: '63012545079-ccr7fi36qpho4it4ro0i8lg7a6fk7bs2.apps.googleusercontent.com',
    iosBundleId: 'com.dcplaforma.edu',
  );
}
